"""Initial schema: current models plus settlement_messages.stream_entry_id.

Revision ID: 0001_initial
Revises:
Create Date: 2026-09-07 12:12:23.642954

Patch B: do not rewrite this revision. Add a new file with down_revision = '0001_initial'.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_initial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fee_config',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('fixed_fee_zar', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('percentage_fee', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('fx_margin_percentage', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('cash_out_fee_percentage', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('limit_tiers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tier_key', sa.Enum('UNVERIFIED', 'VERIFIED', name='limittierkey'), nullable=False),
    sa.Column('daily_limit_zar', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('monthly_limit_zar', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tier_key')
    )
    op.create_table('platform_wallet',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('classic_address', sa.String(length=64), nullable=False),
    sa.Column('secret', sa.String(length=500), nullable=False),
    sa.Column('network', sa.String(length=32), nullable=False),
    sa.Column('trustline_established', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('classic_address')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('mobile_number', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('CUSTOMER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_mobile_number'), ['mobile_number'], unique=True)

    op.create_table('beneficiaries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sender_id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('mobile_number', sa.String(length=32), nullable=True),
    sa.Column('email_address', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('payout_currency', sa.String(length=10), nullable=False),
    sa.Column('relationship_to_sender', sa.String(length=100), nullable=False),
    sa.Column('linked_user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['linked_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('beneficiaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_beneficiaries_linked_user_id'), ['linked_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_beneficiaries_sender_id'), ['sender_id'], unique=False)

    op.create_table('cash_out_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('rlusd_amount', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('fiat_currency', sa.String(length=10), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('cash_out_fee_percentage', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('fee_amount_rlusd', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('fiat_payout_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'APPROVED', 'COMPLETED', 'FAILED', name='cashoutstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actioned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actioned_by', sa.String(length=36), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actioned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cash_out_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_out_requests_user_id'), ['user_id'], unique=False)

    op.create_table('kyc_applications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('nationality', sa.String(length=100), nullable=False),
    sa.Column('identification_number', sa.String(length=500), nullable=False),
    sa.Column('residential_address', sa.Text(), nullable=False),
    sa.Column('mobile_number', sa.String(length=32), nullable=False),
    sa.Column('email_address', sa.String(length=255), nullable=False),
    sa.Column('source_of_funds', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('NOT_SUBMITTED', 'PENDING', 'APPROVED', 'REJECTED', name='kycstatus'), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('recipient_wallets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('xrpl_address', sa.String(length=64), nullable=True),
    sa.Column('secret', sa.String(length=500), nullable=True),
    sa.Column('trustline_established', sa.Boolean(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_token'), ['token'], unique=True)

    op.create_table('remittances',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sender_id', sa.String(length=36), nullable=False),
    sa.Column('beneficiary_id', sa.String(length=36), nullable=False),
    sa.Column('zar_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('fx_margin_percentage', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('transaction_fee_zar', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('rlusd_amount', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('cash_out_fee_percentage', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('estimated_cash_out_fee', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('estimated_recipient_payout', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('status', sa.Enum('QUOTED', 'CASH_IN_PENDING', 'CASH_IN_CONFIRMED', 'SETTLEMENT_QUEUED', 'SETTLED', 'SETTLEMENT_FAILED', name='remittancestatus'), nullable=False),
    sa.Column('cash_in_method', sa.Enum('AGENT_CASH', 'BANK_TRANSFER', 'CARD', name='cashinmethod'), nullable=True),
    sa.Column('cash_in_initiated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cash_in_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cash_in_confirmed_by', sa.String(length=36), nullable=True),
    sa.Column('xrpl_settlement_tx_hash', sa.String(length=96), nullable=True),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settlement_failure_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiaries.id'], ),
    sa.ForeignKeyConstraint(['cash_in_confirmed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('remittances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_remittances_sender_id'), ['sender_id'], unique=False)

    op.create_table('settlement_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('remittance_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='settlementmessagestatus'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('stream_entry_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['remittance_id'], ['remittances.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('remittance_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settlement_messages')
    with op.batch_alter_table('remittances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_remittances_sender_id'))

    op.drop_table('remittances')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_token'))

    op.drop_table('sessions')
    op.drop_table('recipient_wallets')
    op.drop_table('kyc_applications')
    with op.batch_alter_table('cash_out_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_out_requests_user_id'))

    op.drop_table('cash_out_requests')
    with op.batch_alter_table('beneficiaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_beneficiaries_sender_id'))
        batch_op.drop_index(batch_op.f('ix_beneficiaries_linked_user_id'))

    op.drop_table('beneficiaries')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_mobile_number'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('platform_wallet')
    op.drop_table('limit_tiers')
    op.drop_table('fee_config')
    # ### end Alembic commands ###
